# Generated by Django 3.2 on 2021-04-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name'], 'verbose_name': '   Город', 'verbose_name_plural': '   Города'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': '    Страна', 'verbose_name_plural': '    Страны'},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'verbose_name': ' Объект', 'verbose_name_plural': ' Объекты'},
        ),
        migrations.AlterModelOptions(
            name='street',
            options={'ordering': ['name'], 'verbose_name': '  Улица', 'verbose_name_plural': '  Улицы'},
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='location.country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='object',
            name='appartment',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Квартир'),
        ),
        migrations.AlterField(
            model_name='object',
            name='campus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Корпус'),
        ),
        migrations.AlterField(
            model_name='object',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='object',
            name='entrance',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Подъездов'),
        ),
        migrations.AlterField(
            model_name='object',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Этажей'),
        ),
        migrations.AlterField(
            model_name='object',
            name='home',
            field=models.CharField(max_length=255, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='object',
            name='street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='street_objects', to='location.street', verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='street',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_streets', to='location.city', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='street',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
