# Generated by Django 3.2 on 2021-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='appartment',
            field=models.IntegerField(blank=True, null=True, verbose_name='Квартир'),
        ),
        migrations.AlterField(
            model_name='object',
            name='entrance',
            field=models.IntegerField(blank=True, null=True, verbose_name='Подъездов'),
        ),
        migrations.AlterField(
            model_name='object',
            name='floor',
            field=models.IntegerField(blank=True, null=True, verbose_name='Этажей'),
        ),
    ]
