# Generated by Django 3.2 on 2021-06-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20210515_1938'),
    ]

    operations = [

    ]
