# Generated by Django 3.2 on 2021-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_object_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='appartment_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Квартир'),
        ),
        migrations.AddField(
            model_name='object',
            name='entrance_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Подъездов'),
        ),
        migrations.AlterUniqueTogether(
            name='object',
            unique_together={('street', 'home', 'campus', 'floor', 'entrance_number', 'appartment_number')},
        ),
        migrations.RemoveField(
            model_name='object',
            name='appartment',
        ),
        migrations.RemoveField(
            model_name='object',
            name='entrance',
        ),
    ]
