# Generated by Django 3.2 on 2021-04-18 06:22

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('users', '0003_auto_20210417_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
            ],
            options={
                'verbose_name': 'administrator',
                'verbose_name_plural': 'administrators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
            ],
            options={
                'verbose_name': 'moderator',
                'verbose_name_plural': 'moderators',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.customuser',),
        ),

        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default="+3123123123", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
