# Generated by Django 3.2 on 2021-04-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        ('users', '0004_auto_20210418_1022'),
    ]


    
