# Generated by Django 3.2 on 2021-04-18 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('service', '0002_auto_20210418_1548'),
        ('users', '0006_auto_20210418_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('total_square', models.FloatField(blank=True, null=True)),
                ('living_square', models.FloatField(blank=True, null=True)),
                ('share', models.FloatField(blank=True, null=True)),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='location.object')),
            ],
        ),
    ]
