# Generated by Django 3.2 on 2021-04-22 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('location', '0002_auto_20210418_1548'),
        ('users', '0009_auto_20210418_2108'),
    ]

    operations = [

        migrations.AlterField(
            model_name='customuser',
            name='object',
            field=models.ManyToManyField(blank=True, to='location.Object', verbose_name='Объекты'),
        ),
        migrations.CreateModel(
            name='ClientAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_client', to='users.account')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_accounts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
