# Generated by Django 3.2 on 2021-04-22 16:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0010_auto_20210422_2017'),
    ]

    operations = [

        migrations.DeleteModel(
            name='ClientAccount',
        ),
    ]
