# Generated by Django 3.2 on 2021-04-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('service', '0002_auto_20210418_1548'),
        ('users', '0012_auto_20210422_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account',
            field=models.ManyToManyField(to='users.Account', verbose_name='Лицевой счет'),
        ),

        migrations.AlterField(
            model_name='customuser',
            name='object',
            field=models.ManyToManyField(to='location.Object', verbose_name='Объекты'),
        ),
    ]
