# Generated by Django 3.2 on 2021-04-22 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0015_auto_20210422_2112'),
    ]

    operations = [

    ]
