# Generated by Django 3.2 on 2021-04-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0016_auto_20210422_2112'),
    ]

    operations = [

        migrations.AlterField(
            model_name='organizationworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_organizations', to='users.worker'),
        ),
    ]
