# Generated by Django 3.2 on 2021-04-28 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('location', '0002_auto_20210418_1548'),
        ('users', '0017_auto_20210422_2142'),
    ]

    operations = [

        migrations.AlterField(
            model_name='organizationworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='worker_organizations', to='users.worker', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='ModeratorObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moderator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moderator_objects', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_moderators', to='location.object', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Объект',
                'verbose_name_plural': 'Объекты',
                'unique_together': {('moderator', 'object')},
            },
        ),
    ]
