# Generated by Django 3.2 on 2021-04-28 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0019_auto_20210428_2108'),
    ]

    operations = [


    ]
