# Generated by Django 3.2 on 2021-05-02 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('service', '0002_auto_20210418_1548'),
        ('users', '0022_auto_20210429_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользаватель', 'verbose_name_plural': 'Пользавательи'},
        ),

        migrations.AlterField(
            model_name='account',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_accounts', to='location.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_clients', to='users.account'),
        ),
    ]
