# Generated by Django 3.2 on 2021-04-30 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0022_auto_20210429_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ManyToManyField(to='service.Organization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.ManyToManyField(to='service.Service', verbose_name='Обязанности'),
        ),
        migrations.AlterField(
            model_name='clientaccount',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_clients', to='users.account'),
        ),
    ]
