# Generated by Django 3.2 on 2021-05-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('service', '0002_auto_20210418_1548'),
        ('users', '0023_auto_20210502_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='object',
            field=models.ManyToManyField(related_name='object_moderators', to='location.Object', verbose_name='Объекты'),
        ),
    ]
