# Generated by Django 3.2 on 2021-05-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0024_auto_20210502_1943'),
    ]

    operations = [

    ]
