# Generated by Django 3.2 on 2021-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210418_1548'),
        ('users', '0025_auto_20210504_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='organization',
            field=models.ManyToManyField(to='service.Organization', verbose_name='Организации'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='specialization',
            field=models.ManyToManyField(to='service.Service', verbose_name='Обязанности'),
        ),
    ]
