# Generated by Django 3.2 on 2021-05-09 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20210509_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='custom_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_user_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ClientAccount',
        ),
    ]
