# Generated by Django 3.2 on 2021-05-12 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.IntegerField(choices=[(1, 'Активный'), (0, 'Новый'), (-1, 'Блокирован')], default=1),
        ),
    ]
