# Generated by Django 3.2 on 2021-05-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210430_0550'),
        ('users', '0031_faktura'),
    ]

    operations = [
    ]
