# Generated by Django 3.2 on 2021-05-24 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20210522_1951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faktura',
            name='object',
        ),
        migrations.AddField(
            model_name='faktura',
            name='account_name',
            field=models.CharField(max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faktura',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_fakturas', to='users.account'),
        ),
    ]
