# Generated by Django 3.2 on 2021-05-24 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20210524_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faktura',
            name='file',
            field=models.CharField(max_length=1000),
        ),
    ]
