# Generated by Django 3.2 on 2021-05-25 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_alter_faktura_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faktura',
            options={'verbose_name': 'Фактура', 'verbose_name_plural': 'Фактуры'},
        ),
        migrations.AlterField(
            model_name='account',
            name='share',
            field=models.FloatField(blank=True, null=True, verbose_name='Доля, %'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=255, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='account_fakturas', to='users.account', verbose_name='Счета'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='account_name',
            field=models.CharField(max_length=255, verbose_name='Счет'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан в'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_fakturas', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='month',
            field=models.IntegerField(choices=[(1, 'Январь'), (2, 'Февраль'), (3, 'Март'), (4, 'Апрель'), (5, 'Май'), (6, 'Июнь'), (7, 'Июль'), (8, 'Август'), (9, 'Сентябрь'), (10, 'Октябрь'), (11, 'Ноябрь'), (12, 'Декабрь')], verbose_name='Месяц'),
        ),
        migrations.AlterField(
            model_name='faktura',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
