# Generated by Django 3.2 on 2021-05-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_merge_0023_auto_20210430_0550_0031_faktura'),
        ('users', '0035_auto_20210525_1945'),
    ]

    operations = [
    ]
