# Generated by Django 3.2 on 2021-06-05 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_customuser_telegram_id'),
        ('users', '0036_merge_20210526_0501'),
    ]

    operations = [
    ]
