# Generated by Django 3.2 on 2021-05-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('news', '0002_auto_20210418_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='objects',
            field=models.ManyToManyField(to='location.Object'),
        ),
    ]
