# Generated by Django 3.2 on 2021-05-02 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_objects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='objects',
            new_name='news_objects',
        ),
    ]
