# Generated by Django 3.2 on 2021-05-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('share', 'Долями'), ('account', 'Голосами')], default='share', max_length=255, verbose_name='Тип голосования'),
        ),
    ]
