# Generated by Django 3.2 on 2021-05-09 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('vote', '0002_alter_vote_vote_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='object_votes', to='location.object'),
        ),
    ]
