# Generated by Django 3.2 on 2021-04-18 11:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20210418_1548'),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Организация', 'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='organizationobject',
            options={'verbose_name': 'Объект', 'verbose_name_plural': 'Объекты'},
        ),
        migrations.AlterModelOptions(
            name='organizationservice',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='inn',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='organizationobject',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='object_organization', to='location.object', verbose_name='Объект'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='contact_email',
            field=models.EmailField(max_length=254, verbose_name='Контактный Эл. почта'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='contact_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='organizationservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_organizations', to='service.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='dative',
            field=models.CharField(max_length=255, verbose_name='Дательный падеж'),
        ),
        migrations.AlterField(
            model_name='service',
            name='genitive',
            field=models.CharField(max_length=255, verbose_name='Родительный падеж'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='nominative',
            field=models.CharField(max_length=255, verbose_name='Именительный падеж'),
        ),
    ]
