# Generated by Django 3.2 on 2021-05-14 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_alter_ticket_accepted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='ticket/%Y/%m/%d/')),
                ('size', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('waiting', 'На рассмотрении'), ('under_review', 'Принято к исполнению'), ('done', 'Выполнено')], default='waiting', max_length=255),
        ),
        migrations.DeleteModel(
            name='TicketImage',
        ),
        migrations.AddField(
            model_name='ticketfile',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_images', to='ticket.ticket'),
        ),
    ]
