# Generated by Django 3.2 on 2021-06-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_rename_autuserhor_ticketstatushistory_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(choices=[(1, 'На рассмотрении'), (3, 'Принято к исполнению'), (3, 'Выполнено')], default=1),
        ),
        migrations.AlterField(
            model_name='ticketstatushistory',
            name='status',
            field=models.IntegerField(choices=[(1, 'На рассмотрении'), (3, 'Принято к исполнению'), (3, 'Выполнено')]),
        ),
    ]
